### ISSUE TITLE
Episys 2017 Release problems

### ISSUE THREAD

**Issue by Rev2106** [jakepoz/RepDev#10]
Since I can't figure out how to do a pull request properly for the way I fixed them, I'll just describe the issues here and how to fix so you can add to the base code.

1. _Crashes when installing specfiles (also error checker not working)_
When installing a specfile it will crash due to a null pointer.  I've discovered that there is a new message from the host that is throwing off what RepDev expects, but it can be safely ignored, so the fix is to have RepDev keep getting new commands until it finds an "Input" command.  Inside of method errorCheckRepGen of DirectSymitarSession.java, you will see this:
`write("mm3" + (char)27); //Managment menu #3- repgen, of course!!`
`log(readNextCommand().toString());`
`write("7\r");`
Change this to:
`write("mm3" + (char)27); //Managment menu #3- repgen, of course!!`
`while( !(cur = readNextCommand()).getCommand().equals("Input")) log(cur);`
`write("7\r");`
Same goes for the method installRegen, make it look like this:
`write("mm3" + (char)27); //Managment menu #3- repgen, of course!!`
`while( !(cur = readNextCommand()).getCommand().equals("Input")) log(cur);`
`write("8\r");`
2. _Batch jobs fail to show reports_
I don't know if this is purely a result of 2017, but it seems that if you ask for a count of reports that is larger than the amount listed, the host will send back a "No such file" error message after it is done listing the reports.  This is throwing off RepDev from properly reading the latest Batch Output because it is not dealt with and so it ends up reading the next latest Batch Output because it thinks the latest one doesn't exist.  The fix is to deal with the message should it be there.
In the getPrintItems method in DirectSymitarSession.java, add this after the while loop which is listing the report files:
`if(in.ready()) { cur = readNextCommand(); log(cur); }`
This will check if the input stream has anything, and if so, it will basically discard it, as it does not need to be handled.

I don't know of any other issues since implementing these in my fork, but let me know if there's anything else and I can take a look as I have time.

**Comment by thechillman422** [comment]
Hi Eric, Can you at least push the changes to your repository so I can take a look and then I can update the code accordingly.  Thanks, I appreciate it.

**Comment by Rev2106** [comment]
Yeah, here's the link to the file:

https://github.com/Rev2106/RepDev/blob/2b1fdcfa8707b24751b5f037fca07a28a496efd3/com/repdev/DirectSymitarSession.java

**Comment by thechillman422** [comment]
Thanks Eric.  I will take a look.  How long have you tested your change and have you had anyone else test the changes to see if it fix the issue for them as well?  Thanks.

Bruce.

**Comment by Buckmarble** [comment]
I just ended up doing a build with @Rev2106 changes and everything seems to be working in 2016 and 2017. I can install and run batch reports and the reports open.

**Comment by Rev2106** [comment]
Well, there you go!  I just confirmed with an associate of mine that it works for him too.  I did just enough testing to make sure it fixed those issues.

**Comment by Vysion34** [comment]
I just got done testing Eric's suggested fixes and I am successfully able to use error checking, run specfiles, , receive the report output, and install specfiles in both 2016 and 2017 Episys.

**Comment by thechillman422** [comment]
Thanks Eric for your patch.  I'm going to close this out.
