### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by PvtFrenchie** [jakepoz/RepDev#13]
This version seems to lock up on windows 10 after you attempt to log into a sym.  i have downloaded it on windows 7 and it runs just fine.

**Comment by thechillman422** [comment]
I've used it on Windows 10, that should not be the issue.  Are you using SSH and did you cache the SSH Key?  what is the content of stderr.txt and the content of stdout.txt.
P.S. if you post it on SMUG, you may get more response/help.

**Comment by PvtFrenchie** [comment]
I would like to close this error.  it was our fault, there was some permissions issue that was causing the problem.

**Comment by thechillman422** [comment]
Glad to hear your issue has been resolved.  Thanks for letting me know.
