### ISSUE TITLE
Old db.txt version in 1.6.12

### ISSUE THREAD

**Issue by kcjenks** [jakepoz/RepDev#14]
Hey there, a minor thing, but I noticed the db.txt packaged with the 1.6.12 zips is a couple years old and missing some recent field additions. 
Thanks!

**Comment by thechillman422** [comment]
That is correct.  I will be loading Release 2017 this Saturday.  I should have the db updated sometime next week.  I will send a message on SMUG when that is done.

**Comment by thechillman422** [comment]
This was updated last week.
