### ISSUE TITLE
Refresh File feature request

### ISSUE THREAD

**Issue by garrcarv** [jakepoz/RepDev#15]
Hello,

I use RepDev frequently and think it would be very helpful to have a "refresh file" option or keyboard shortcut. If a file being worked on is modified elsewhere we could refresh it without needing to search for it in the SYM again. This would be handy when working on programs that read and write to letter/help files.

Thanks for the great program!
gc

**Comment by thechillman422** [comment]
Hi gc,  I don't really understand what you mean by "if a file being worked on is modified elsewhere we could refresh it without needing to search for it in the SYM again".
1.  If you are working on a file and someone else is also working on it, how can you refresh your copy unless you use source control.
2. Why would you need to search for it in the SYM again.  You can create projects in RepDev to keep your RepGens grouped and available with a click.  Well, more like double click ;P
Please elaborate on your suggestion.  or let me know your email and I can email you directly to clear up any questions.  Thanks.

**Comment by garrcarv** [comment]
I was thinking primarily about help/letter files. Specifically, I am working on code that reads and writes to a letter file. My setup thus far has been running the program in Episys and looking at the code and the letter file output in RepDev. It sounds like I should look into the benefits of using projects more, but in order to reload the letter file I've been closing it out and then navigating through the letter file search menu to reopen it. So I was thinking it would be handy to have a quick keyboard shortcut or something to just refresh the letter file to see the new output. Thank you for the quick response! :)

**Comment by JacobClouse** [comment]
So the use case would be 

1. File (any type) is open in editor
2. File is changed on host/sym
3. User clicks a "refresh" button to bring in the remote changes to editor without having to re-open file

Is that correct?

**Comment by garrcarv** [comment]
Yes, that is correct.

**Comment by thechillman422** [comment]
Since I had some time over the 4 day break, I added your request.  in the next release, or if you want to build it yourself, you can press F5 in the editor window and the file will close and reopen.  I will go ahead and close this issue.
