### ISSUE TITLE
Surround Text Dialog Bug

### ISSUE THREAD

**Issue by faithfulman18** [jakepoz/RepDev#17]
I find the 'Surround Text Dialog' option in RepDev is very handy, in particular for adding in htmlviewline's.  However, on some of my larger repgen files, I kept running into an issue and only recently discovered it was only happening when I run the 'Surround Text Dialog' function.  

The issue is that when you run that command, it seems to remove the carriage returns and spacing out of the rest or at least parts of the specfile.  

We commit all of our repgen code into a GIT repository, so for some of the larger files in particular it becomes frustrating, to have to go through the DIFFS and figure out what things are real changes and other "DIFFS" are just repdev removing spacing and carriage returns.

Honestly, if it was just spaces as in extra spaces at the end of the line, I wouldn't mind it and maybe even be happy with that, but the carriage returns being removed so my various procedures no longer have space between them is incredibly annoying.

Is this something that could be fixed?

Thanks,

Kevin

**Comment by thechillman422** [comment]
Kevin,  What value do yo have in the 2nd box (After).  That normally contains a \n, which is a carriage return.  It would affect your code if you inadvertently removed it.  Example with HTMLVIEWLINE; in the 1st box (Before), you should have **HTMLVIEWLINE("**
In the 2nd box (After), you should have **")\n**
Let me know if that may be the cause because I've not experienced the issue that you have.

**Comment by faithfulman18** [comment]
No, I enter this in the first box:
HTMLVIEWLINE("

and this is the 2nd box:
")\n

Just as you mentioned above.  Maybe it has to do with some of the files being very large?  Like 5K lines of code?

I'm not sure sure, but all the carriage returns between my procedures dissapear.  I can reproduce it over and over.

**Comment by faithfulman18** [comment]
Another thing that is weird is as soon as I push OK on the surround text popup, it moves me away from my position in the code (besides all the carriage returns being removed)

**Comment by thechillman422** [comment]
Questions;
1. Are you able to reproduce it with any RepGen or mostly large 5K line RepGens.
2. How many lines are selected when you are using Surround with, ball park, 10, 50, 100, 5K?
3. What version are you using when this happens? I assume it happens with 1.6.14beta as well?

**Comment by thechillman422** [comment]
Oh, and you didn't accidentally press Ctrl+Shift+T instead of Ctrl+Shift+R did you?  I know Ctrl+Shift+T is the Format Code (BETA), but was never perfected :P

**Comment by faithfulman18** [comment]
It doesn't seem to happen the same way on smaller repgens, but I just tried it on two other repgens that were just over 1000K and it happened with those.  On real small files with a small amount of lines of code, it doesn't seem to happen the same way sometimes removing 1 or none carriage returns.

I was able to get it happen when just selecting 2 lines of html that I just pasted in, but most of my tests have been about 15 lines.  So, I'm thinking the amount of lines doesn't matter.

Yes, I was testing with 1.6.14beta.  However, I've noticed this issue for some time, not knowing what was causing it until recently, but I believe this has been a bug for a long time.

No, I was highlighting the HTML I just pasted in, right clicked the selected text and chose Surround Text Dialog.

**Comment by thechillman422** [comment]
Ok, I was able to duplicate the issue with TT.CF this morning.  I'll try to take a look at it this weekend and see how easy it would be to fix that.  I'll get back to you.

**Comment by faithfulman18** [comment]
Great.  Thanks!  Hopefully, it's not too difficult.

**Comment by thechillman422** [comment]
It took me 30 minutes to find the bug. It took me 2 seconds to fix it :P
Same as the previous beta build, archive the current com folder and replace it with the one in this zip file.  This will be 14beta3
https://app.box.com/s/cj4rwohlzky2uevf4dzltcf04lypu2dy
