### ISSUE TITLE
String Index Out of Range Exception When Creating a New PowerOn or Importing an Existing into a Project

### ISSUE THREAD

**Issue by cilleyperson** [jakepoz/RepDev#2]
RepDev: 1.6.10

Error Text: String index out of range: 0 - java.lang.StringIndexOutOfBoundsException
Tue Jun 23 08:35:07 EDT 2015

java.lang.String.charAt(Unknown Source)
com.repdev.SymitarSession.getUserNum(SymitarSession.java:374)
com.repdev.SymitarSession.getUserNum(SymitarSession.java:363)
com.repdev.ProjectManager.saveProjects(ProjectManager.java:143)
com.repdev.MainShell.importFiles(MainShell.java:752)
com.repdev.MainShell.access$17(MainShell.java:715)
com.repdev.MainShell$25.widgetSelected(MainShell.java:1661)
org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
com.repdev.RepDevMain.main(RepDevMain.java:93)

User Notes: 

This occurs any time I attempt to create a new PowerOn within the RepDev environment. It works fine in 1.6.9 but not in 1.6.10

**Comment by thechillman422** [comment]
What Teller Number are you using?

**Comment by thechillman422** [comment]
I did not get a response from cilleyperson, but I assume he was using user zero.  I patched it so I'm closing this out.  If it does not fix your issue, please contact me on SMUG.
