### ISSUE TITLE
Open Sym Icon

### ISSUE THREAD

**Issue by gcarversynergent** [jakepoz/RepDev#20]
Hello, this isn't really an issue but I figured it might be useful.

I had a hard time distinguishing the "on" syms in the sym list. I updated the "small-sym-on.png" icon to be a little more distinct.

Attached is the png file if you'd like to use it.

Garrett

![small-sym-on](https://user-images.githubusercontent.com/46356731/63624776-91672600-c5cb-11e9-993d-caf9572a2797.png)

**Comment by thechillman422** [comment]
This has been updated.  Thanks.
