### ISSUE TITLE
Quality of life tweaks

### ISSUE THREAD

**Issue by gcarversynergent** [jakepoz/RepDev#22]
Hello, I have a couple of small requests just to improve UI.

1) Add a "sort by sym number" option to the column listing syms.
2) When logging into a sym that already exists in the column of listed syms via the "Sym login" button rather than clicking on the list, the icon next to the listed sym does not properly update to green to indicate you're logged in.  Could this be fixed?

Thank you for your consideration,
Garrett

**Comment by thechillman422** [comment]
1. The SYM Number should sort every time you close and reopen RepDev.  What version are you using?

2. I'm not understanding #2, what do you mean by Sym login button, can you send a screenshot?

Thanks.

**Comment by gcarversynergent** [comment]
I was on 1.6.13 - sorry for forgetting to update my version before posting these questions.  I have updated to 1.7 now.

1. This is working as you described.  Great!
2. Still an "issue" - see screenshot.  I should have said the "Add a new Sym to this list" button. See below example.

Say I don't notice that a sym is already in the list, and try to login via the "Add a new Sym to this list" button.  It will successfully log me in, but no sym will appear.  Then I need to scan through my listed syms to find the right number because the icon does not turn green.  In the screenshot you can see I am indeed logged into sym 801 because I have the option to log out, but the icon is still gray.

![repdev_screenshot](https://user-images.githubusercontent.com/46356731/75901501-9b849f80-5e0c-11ea-9600-8ef79960b435.jpg)

**Comment by thechillman422** [comment]
Thanks for the screenshot, it really helps.  I was able to duplicate your issue.  I got a patch for it.  I will test it for a few days, then commit it.

**Comment by gcarversynergent** [comment]
Awesome, thank you!

**Comment by thechillman422** [comment]
Garrett, this has been patched and committed.  I hope the Quality of life improves for you :D 
I know my quality of live has improved... I finally found a 4 pack of toilet paper ;P
5 years from now, no one will understand the comment.
