### ISSUE TITLE
not responding when try to open sym

### ISSUE THREAD

**Issue by kbickler** [jakepoz/RepDev#23]
I haven't used RepDev in a while because it kept freezing when I tried to open a sym.  Today I downloaded version 1.7.0 (64 bit version).  It freezes (not responding error) when I try to open a sym.  I am using the SSH connection.  Can you give me some direction to get this working?  I love this program but haven't been able to use it for about a year.

Thanks,
Kim

**Comment by thechillman422** [comment]
How do I get a hold of you to help troubleshoot? are you on SMUG?

**Comment by kbickler** [comment]
Yes I am.

**Comment by thechillman422** [comment]
Sorry I cannot find you on SMUG.  Please send an email to SMUG IT with the subject line RepDev Freezing and I will respond to that thread.  Thanks.

Bruce.

**Comment by kbickler** [comment]
Thank you Bruce for the help.  I got in. The Beta version works.
