### ISSUE TITLE
Live SYM background color improperly coloring files from local mounted folders

### ISSUE THREAD

**Issue by JeffreyHartman** [jakepoz/RepDev#24]
I use locally mounted folders in RepDev to store my files in a git folder. My live SYM is set to 0, any my files opened from locally mounted folders are improperly showing with the set background color.

**Comment by thechillman422** [comment]
Good catch Jeffrey.  Our live inst is not zero so I didn't catch it.  I'll get a patch out for it.  Thanks.

**Comment by thechillman422** [comment]
Jeffrey, this has been patched and committed.  Thanks for reporting the bug.
