### ISSUE TITLE
Syntax highlight support for subfield variables

### ISSUE THREAD

**Issue by pjvinson** [jakepoz/RepDev#25]
Hello,

When writing a subfield such as NOTE:TEXT:1, it is also possible to use a variable name in parens, as such:

NOTE:TEXT:(X) 

But the syntax highlighter marks it as an error.  Could support for this be added?

**Comment by thechillman422** [comment]
This issue has nagged me for years as well.  I can try to take a look, but I don't think I'll have much success, as I'm not a seasoned java programmer.  Hopefully other code contributors out there can take a look as well and have better luck than me.

**Comment by thechillman422** [comment]
Ok, 4 years later... I finally got to it :D This has been included in Release 1.7.5.  I will go ahead and close out this issue.

Bruce
