### ISSUE TITLE
Jump to Definition crash

### ISSUE THREAD

**Issue by pjvinson** [jakepoz/RepDev#26]
Hello!  

I sometimes get an app crash when using ctrl-shift-G to jump to the definition of an item.
I see txaustin has a patch on his fork here that could be applicable.

https://github.com/txaustin/RepDev/commit/e3457aac99e6288ac56803999dd4b2067593b3d4

**Comment by thechillman422** [comment]
Hi, I've never used Ctrl-Shift-G to jump to the definition, so I've never experienced this crash.  If this happens frequently for you, could you post the error message you received.

P.S. you referenced txaustin's patch, but the comment states "Fixed crash when double clicking CALL to goto procedure".  That's an entirely different issue.

**Comment by pjvinson** [comment]
Oh, sorry.  It's the same error, I think, it mentions hashmap.  I should have included that, I'll grab it next time.

**Comment by pjvinson** [comment]
So I was totally wrong about the error mentioning hashmap.  Here's the error.  Easy repo:

Press ctl-shift-G in any repgen while you also have a report output tab open.

```
RepDev: 1.7

Error Text: com.repdev.ReportComposite cannot be cast to com.repdev.EditorComposite - java.lang.ClassCastException
Thu Apr 30 12:01:31 PDT 2020

com.repdev.EditorComposite.gotoDefinition(EditorComposite.java:1308)
com.repdev.EditorComposite$8.keyPressed(EditorComposite.java:897)
org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:171)
org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1064)
org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1106)
org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1102)
org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1489)
org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4888)
org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:353)
org.eclipse.swt.widgets.Control.windowProc(Control.java:4768)
org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
org.eclipse.swt.widgets.Display.windowProc(Display.java:4784)
org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2309)
org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3559)
com.repdev.RunReportShell.open(RunReportShell.java:484)
com.repdev.MainShell.runReport(MainShell.java:2283)
com.repdev.EditorComposite$8.keyPressed(EditorComposite.java:838)
org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:171)
org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1064)
org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1106)
org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1102)
org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1489)
org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4888)
org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:353)
org.eclipse.swt.widgets.Control.windowProc(Control.java:4768)
org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
org.eclipse.swt.widgets.Display.windowProc(Display.java:4784)
org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2309)
org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3559)
com.repdev.RepDevMain.main(RepDevMain.java:93)
com.repdev.launcher.Launcher.main(Launcher.java:46)

```

**Comment by thechillman422** [comment]
I was not able to duplicate it.  I opened a RepGen, then I opened the last ran report.  Went back to the RepGen, press Ctrl-Shift-G and it did not crash.  I tried several times with various variables and did not get it to crash.  From the Trace, it looks like Ctrl-R was pressed, and then Ctrl-Shift-G was pressed.  What was your sequence of event/keystroke?

**Comment by pjvinson** [comment]
Steps:
Open a simple RG.  
Run it with ctrl-R
Switch tab back to RG
Hit ctrl-shift-G on any ordinary word

Thanks for looking into this.  I tried a few more tests, the ctrl-R keystroke is not necessary, it also happens if I open a report via "open last report run,"  I only get a crash if I press ctrl-shift-G on something that is actually *not* a variable or procedure.  (In my use case, they were vars but I think I was in a .pro file and repdev didn't know where to find the definition.)

**Comment by thechillman422** [comment]
Sorry, I know it's been 11 months.  I was finally able to duplicate your issue.  Of course it would help If I'd read your notes carefully.  The issue is that if the variable declaration is not found in the current RepGen, it will go thru each tab of opened files to check for the declaration.  The problem occurs when it encounters a Report and tries to read it like a RepGen.  RepDev now checks to make sure the tab contains an Editor Composite before trying to read it.
