### ISSUE TITLE
Number Format Exception in Live Sym Background Color Setting

### ISSUE THREAD

**Issue by mattle** [jakepoz/RepDev#27]
RepDev: 1.7

Error Text: For input string: "#f" - java.lang.NumberFormatException
Tue Mar 02 09:12:03 PST 2021

java.lang.NumberFormatException.forInputString(Unknown Source)
java.lang.Integer.parseInt(Unknown Source)
com.repdev.SyntaxHighlighter.getRGB(SyntaxHighlighter.java:352)
com.repdev.SyntaxHighlighter.<init>(SyntaxHighlighter.java:109)
com.repdev.EditorComposite.buildGUI(EditorComposite.java:535)
com.repdev.EditorComposite.<init>(EditorComposite.java:197)
com.repdev.MainShell.openFile(MainShell.java:466)
com.repdev.MainShell.doubleClickTreeItem(MainShell.java:548)
com.repdev.MainShell.access$18(MainShell.java:538)
com.repdev.MainShell$32.widgetDefaultSelected(MainShell.java:1952)
org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
com.repdev.RepDevMain.main(RepDevMain.java:93)
com.repdev.launcher.Launcher.main(Launcher.java:46)

User Notes: 
This was a result of me leaving a leading pound sign in the value entered into "Live SYM background Color" under "Editor Options" in the settings.

To reproduce:
1. Enter a value for "Live SYM background Color" that starts with a pound sign like "#dd5283".
2. Click "Save Settings" button.
3. Open any file on live sym.

**Comment by thechillman422** [comment]
Thank you for reporting the issue.  I've patched it to make sure there are 6 hexadecimal characters.  An error message would popup and at the same time, the default value will be set.
