### ISSUE TITLE
Multi Line Prompts Issue & Crash

### ISSUE THREAD

**Issue by gcarversynergent** [jakepoz/RepDev#29]
Hello,

When working with reports that use multi-line prompts the formatting is broken when filling out the prompts in the Run Report window (see attached file formatting_issue.jpg). A report with two or three multi-line prompts can cause the Run Report window to extend beyond the user's screen (see overflow.jpg). I have attached the test specfile I used to create the issue screenshots - see attached test1.txt

When taken to the extreme this will eventually cause repdev to hang, requiring a force quit (see crash.jpg). This is rare but we do have a couple reports where this is a problem. I attached another specfile that can be used to recreate this crash - see attached test2.txt

I am using the latest release of repdev (1.7.0 32 bit).

Let me know if you need any additional information,
Garrett

[test1.txt](https://github.com/jakepoz/RepDev/files/6610063/test1.txt)
[test2.txt](https://github.com/jakepoz/RepDev/files/6610064/test2.txt)

formatting_issue.jpg
![formatting_issue](https://user-images.githubusercontent.com/46356731/121041093-6fc73680-c780-11eb-9ee6-5faefe92c1a1.jpg)

overflow.jpg
![overflow](https://user-images.githubusercontent.com/46356731/121041094-705fcd00-c780-11eb-996a-2077411d076e.jpg)

crash.jpg
![crash](https://user-images.githubusercontent.com/46356731/121041091-6fc73680-c780-11eb-9e28-5d8ded22cb1c.jpg)

**Comment by thechillman422** [comment]
Hi, I just pushed out version 1.7.1 with the fix.  I'll go ahead and close the case.  please reopen the case if the new version does not fix the prompt issue.  Thanks.

**Comment by gcarversynergent** [comment]
It works great, thank you!
