### ISSUE TITLE
Tasks Display Strangeness

### ISSUE THREAD

**Issue by mattle** [jakepoz/RepDev#30]
When there are multiple tasks in a file, sometimes the closing bracket and following text on that line are included in the list of tasks. I am using RepDev v 1.7.1 on a Windows 10 machine. A couple examples are shown below:

![6eec72b3-ab3b-41fa-8919-a5a76b394865](https://user-images.githubusercontent.com/112625/163235917-d5a3e3f2-eb5b-4fcf-be16-f45484497c17.jpg)

![image](https://user-images.githubusercontent.com/112625/163236916-2be4af47-44b0-48e7-b479-45a5ab2d2e51.png)

**Comment by mattle** [comment]
Looks like it won't happen if there is actual code following the comments, but still happens if the code is before the comments:

![image](https://user-images.githubusercontent.com/112625/163238787-aa876223-de85-40c1-a459-a80a3ea4c705.png)

![image](https://user-images.githubusercontent.com/112625/163238611-1e0ce5d5-695f-4f04-979a-1e13361ff820.png)

**Comment by thechillman422** [comment]
Hi, this bug has been around forever.  I'll try to take a look when I get a chance.

**Comment by thechillman422** [comment]
This has been patched and will be included in the next release.  After the release, if it still doesn't work, you may reopen this issue.
