### ISSUE TITLE
Newer Launch4j Needed for Alternate JREs

### ISSUE THREAD

**Issue by ryhcu404** [jakepoz/RepDev#35]
When repdev.exe is ran with certain JRE installations (e.g. Eclipse Temurin JRE), the JRE requirement popup message pops up each time and then the program closes:

> **Launch4j**
> This application requires a Java Runtime Environment 1.5.0
> **OK**

The start.bat works around this issue somehow, but is not ideal due to command window that remains open.

One actual solution is to compile the repdev.exe with the newest (or a newer) build of Launch4j. I tried this with version 3.50 and it worked.

A possible other solution might be to remove the minVersion (1.5.0) value altogether from launch4j.xml.

**Comment by thechillman422** [comment]
RepDev.exe has been rebuilt per your recommendation and tested by JHennessy.  The new RepDev.exe has been committed to repo.  Thank you very much.
