### ISSUE TITLE
RepDev - 1.6.14_64Bit, 1.7.2_64Bit, and 1.7.4_64Bit 'Not Responding'

### ISSUE THREAD

**Issue by AbsurdEnigma** [jakepoz/RepDev#37]
Wondering if I can get some help on how to go about RepDev going to not responding.  I verified my .config file is fine as I have this working on other computers as well as the java version and ran through some troubleshooting to try and save the ssh key, but that doesn't seem to be saving or creating.  What next steps should I take?

**Comment by ryhcu404** [comment]
Fwiw, I had RepDev hanging up on our Prod server (Test server was fine) starting last week, but running the Cache_SSH_Key.bat tool (same dir as the .exe) fixed it.

**Comment by thechillman422** [comment]
Hi AbsurdEnigma, if you are on SMUG listserv, you will get better response from there.
What is the last message in stdout.txt?
Try moving repdev.conf out of the folder and start from scratch.  Add one sym for testing.

**Comment by AbsurdEnigma** [comment]
@thechillman422 that's a great question I should be more thoughtful in my response!  The output from the file stdout.txt is, 'If this is the last message you see, you may need to cache your SSH Key.
For help, see the Wiki Page at https://github.com/jakepoz/RepDev/wiki/Using-SSH' I did try this, however, there's no key that prompts to cache.  I tried with a config I know works in our environment and fresh and both result in the same stop.  I also tried @ryhcu404's suggestion for Cache_SSH_Key.bat and I was able to run through this, but still goes to the same spot.  The one thing I haven't tried is manually creating the key in the registry.  I see there can be a Putty cached SSH Key
[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\SshHostKeys]
"rsa2@22:symitar"="0x10001,YOURHOSTSSHKEYHERE" created, but would I just replace the 'YOURHOSTSSHKEYHERE' with the SYM name?  Apologies this is a bit out of my wheelhouse and I'm trying to help out and learn!

**Comment by thechillman422** [comment]
@AbsurdEnigma Let's start fresh

1. Download version 1.7.4 again
2. right click on the zip file, select property and check the box that says Unblock, click ok
3. unzip the content
4. In the RepDev folder, double click on AIX_Term.reg to add the Registry information
5. Double click on Cache_SSH_Key.bat and enter the hostname of your **test server**
6. Log into your test server
7. Close out of the command window
8. Launch RepDev
9. In Settings, set the hostname of your **test server** for the Symitar Server IP Address
10. set the port to 22
11. Click Save Settings
12. Close RepDev
13. Launch RepDev
14. Click the "Add a new Sym" icon
15. Enter the information for one of your test SYMs and log in

let me know if that helps

Bruce

**Comment by AbsurdEnigma** [comment]
Thank you @thechillman422!  That worked for me checking to see if that'll work for others appreciate you so much!

**Comment by thechillman422** [comment]
@AbsurdEnigma Glad it works for you.  I will go ahead and close this issue.  Let me know if you need anything else.

Bruce
