### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by JacobClouse** [jakepoz/RepDev#40]
Any desire to have Gradle added to the project to handle dependency management and build tasks? I'm happy to submit a PR but didn't want to start work on that without asking first.

**Comment by thechillman422** [comment]
Hi Jacob.  At this point, I would have to say no.  Thank you tho.  Currently, I am the only active contributor and I use "active" very loosely :) Right now, everything works well for me in Eclipse. I click build, and everything is in the dist folder.  Not that many dependencies.  Thanks again.

**Comment by JacobClouse** [comment]
Good deal, thanks for letting me know. I'll close this.
