### ISSUE TITLE
Logon Issue

### ISSUE THREAD

**Issue by imcgraw49** [jakepoz/RepDev#5]
![logon issue](https://cloud.githubusercontent.com/assets/20442349/16808880/4a50d4be-48ec-11e6-885b-9d001b0a1fd8.jpg)
When attempting to login, if sym in unavailable Repdev hangs instead of returning an error. Screenshot is the error message you would get from attempting to login from Symitar.

**Comment by thechillman422** [comment]
If you grab a RAS Trace, I can try to patch it, but it does not seem like a common error.  Why do you get that error?  Is the SYM down, or you don't have proper access to it?

**Comment by thechillman422** [comment]
I've added a catch all logic to handle any SYM errors.
